<center>
    <img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/assets/logos/SN_web_lightmode.png" width="200" alt="cognitiveclass.ai logo">
</center>

# Machine Learning Foundation

## Course 4, Part e: Non-Negative Matrix Factorization DEMO

This exercise illustrates usage of Non-negative Matrix factorization and covers techniques related to sparse matrices and some basic work with Natural Langauge Processing.  We will use NMF to look at the top words for given topics.

## Data

We'll be using the BBC dataset. These are articles collected from 5 different topics, with the data pre-processed. 

These data are available in the data folder (or online [here](http://mlg.ucd.ie/files/datasets/bbc.zip?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMML0187ENSkillsNetwork821-2023-01-01)). The data consists of a few files. The steps we'll be following are:

* *bbc.terms* is just a list of words 
* *bbc.docs* is a list of artcles listed by topic.

At a high level, we're going to 

1. Turn the `bbc.mtx` file into a sparse matrix (a [sparse matrix](https://docs.scipy.org/doc/scipy/reference/sparse.html?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMML0187ENSkillsNetwork821-2023-01-01) format can be useful for matrices with many values that are 0, and save space by storing the position and values of non-zero elements).
1. Decompose that sparse matrix using NMF.
1. Use the resulting components of NMF to analyze the topics that result.

## Data Setup

Note: This lab has been updated to work in skillsnetwork for your convenience.

In [1]:
import urllib

In [2]:
with urllib.request.urlopen('https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-ML0187EN-SkillsNetwork/labs/module%203/data/bbc.mtx') as r:
    content = r.readlines()[2:]

## Part 1

Here, we will turn this into a list of tuples representing a [sparse matrix](https://docs.scipy.org/doc/scipy/reference/sparse.html?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMML0187ENSkillsNetwork821-2023-01-01). Remember the description of the file from above:

* *bbc.mtx* is a list: first column is **wordID**, second is **articleID** and the third is the number of times that word appeared in that article.

So, if word 1 appears in article 3, 2 times, one element of our list will be:

`(1, 3, 2)`

In [3]:
sparsemat = [tuple(map(int,map(float,c.split()))) for c in content]
# Let's examine the first few elements
sparsemat[:8]

[(1, 1, 1),
 (1, 7, 2),
 (1, 11, 1),
 (1, 14, 1),
 (1, 15, 2),
 (1, 19, 2),
 (1, 21, 1),
 (1, 29, 1)]

## Part 2: Preparing Sparse Matrix data for NMF

We will use the [coo matrix](https://docs.scipy.org/doc/scipy/reference/generated/scipy.sparse.coo_matrix.html?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMML0187ENSkillsNetwork821-2023-01-01) function to turn the sparse matrix into an array.

In [4]:
import numpy as np
import pandas as pd
from scipy.sparse import coo_matrix

# each value starts at 1 and python starts at 0, so substract 1
rows = [x[1]-1 for x in sparsemat]
cols = [x[0]-1 for x in sparsemat]
values = [x[2]-1 for x in sparsemat]
coo = coo_matrix((values, (rows, cols)))

In [13]:
with urllib.request.urlopen('https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-ML0187EN-SkillsNetwork/labs/module%203/data/bbc.terms') as r:
    content = r.readlines()
words = [item.decode('utf-8').strip() for item in content]
words[:5]

['ad', 'sale', 'boost', 'time', 'warner']

In [14]:
with urllib.request.urlopen('https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-ML0187EN-SkillsNetwork/labs/module%203/data/bbc.docs') as r:
    content = r.readlines()
docs = [item.decode('utf-8').strip() for item in content]
docs[:5]

['business.001',
 'business.002',
 'business.003',
 'business.004',
 'business.005']

In [15]:
pd.DataFrame(coo.toarray(), columns=words, index=docs)

,ad,sale,boost,time,warner,profit,quarterli,media,giant,jump,...,Â£339,denialofservic,ddo,seagrav,bot,wirelessli,streamcast,peripher,headphon,flavour
business.001,0,4,1,2,3,9,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
business.002,0,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
business.003,0,3,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
business.004,0,0,0,0,0,3,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
business.005,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
tech.397,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
tech.398,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
tech.399,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
tech.400,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
tech.401,0,0,0,21,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

## NMF

NMF is a way of decomposing a matrix of documents and words so that one of the matrices can be interpreted as the "loadings" or "weights" of each word on a topic.

Check out [the NMF documentation](http://scikit-learn.org/stable/modules/generated/sklearn.decomposition.NMF.html?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMML0187ENSkillsNetwork821-2023-01-01) and the [examples of topic extraction using NMF and LDA](http://scikit-learn.org/0.18/auto_examples/applications/topics_extraction_with_nmf_lda.html?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMML0187ENSkillsNetwork821-2023-01-01).

## Part 3

Here, we will import `NMF`, define a model object with 5 components, and `fit_transform` the data created above.

In [19]:
# Surpress warnings from using older version of sklearn:
def warn(*args, **kwargs):
    pass
import warnings
warnings.warn = warn

from sklearn.decomposition import NMF


model = NMF(n_components=5, init='random', random_state=818)
doc_topic = model.fit_transform(coo)

doc_topic.shape
# we should have 2225 observations (articles) and five latent features

(2225, 5)

In [20]:
# find feature with highest value per doc
np.argmax(doc_topic, axis=1)

array([4, 1, 3, ..., 1, 1, 2])

## Part 4: 

Check out the `components` of this model:

In [21]:
model.components_.shape

(5, 9635)

This is five rows, each of which is a "topic" containing the weights of each word on that topic. The exercise is to _get a list of the top 10 words for each topic_. We can just store this in a list of lists.

**Note:** Just like we read in the data above, we'll have to read in the words from the `bbc.terms` file.

In [22]:
topic_words = pd.DataFrame(model.components_.round(3),
                           index = ("topic_1", "topic_2", "topic_3", "topic_4", "topic_5"),
                           columns = words)

topic_words

,ad,sale,boost,time,warner,profit,quarterli,media,giant,jump,...,Â£339,denialofservic,ddo,seagrav,bot,wirelessli,streamcast,peripher,headphon,flavour
topic_1,0.168,0.339,0.000,0.419,0.000,0.058,0.000,0.039,0.000,0.048,...,0.0,0.0,0.000,0.000,0.000,0.0,0.003,0.000,0.0,0.0
topic_2,0.354,0.512,0.072,1.485,0.013,0.148,0.001,0.569,0.031,0.014,...,0.0,0.0,0.037,0.049,0.082,0.0,0.012,0.004,0.0,0.0
topic_3,0.179,0.424,0.004,3.460,0.027,0.002,0.000,0.152,0.019,0.026,...,0.0,0.0,0.000,0.000,0.001,0.0,0.000,0.001,0.0,0.0
topic_4,0.097,0.216,0.049,1.418,0.000,0.147,0.001,0.000,0.006,0.016,...,0.0,0.0,0.000,0.000,0.000,0.0,0.000,0.001,0.0,0.0
topic_5,0.223,0.005,0.061,1.075,0.082,0.055,0.000,0.102,0.000,0.148,...,0.0,0.0,0.000,0.000,0.000,0.0,0.006,0.000,0.0,0.0

The original data had 5 topics, as listed in `bbc.docs` (which these topic words relate to). 

```
Business
Entertainment
Politics
Sport
Tech
```

In "real life", we would have found a way to use these to inform the model. But for this little demo, we can just compare the recovered topics to the original ones. And they seem to match reasonably well. The order is different, which is to be expected in this kind of model.

In [29]:
topic_doc = pd.DataFrame(doc_topic.round(5),
                           index = (i.split('.')[0] for i in docs),
                           columns = ["topic_1", "topic_2", "topic_3", "topic_4", "topic_5"])

topic_doc

          topic_1  topic_2  topic_3  topic_4  topic_5
business  0.00000  0.02640  0.01557  0.00964  0.03487
business  0.00000  0.03848  0.00544  0.01710  0.01375
business  0.00000  0.02036  0.00069  0.02634  0.00000
business  0.02648  0.00835  0.00163  0.07533  0.01134
business  0.00000  0.02329  0.00000  0.00000  0.00048
...           ...      ...      ...      ...      ...
tech      0.00000  0.15878  0.00000  0.00903  0.00000
tech      0.00000  0.13088  0.00000  0.00880  0.00000
tech      0.00000  0.21999  0.00000  0.04542  0.00974
tech      0.00533  0.08742  0.00000  0.00414  0.00000
tech      0.04938  0.00000  3.97397  0.28684  0.00000

[2225 rows x 5 columns]

In [30]:
topic_doc.reset_index().groupby('index').mean().idxmax()

topic_1    entertainment
topic_2             tech
topic_3             tech
topic_4         politics
topic_5    entertainment
dtype: object

In [31]:
topic_words.T.sort_values(by="topic_1", ascending=False)

         topic_1  topic_2  topic_3  topic_4  topic_5
song      11.333    0.000    0.000    0.000    0.000
music     10.833    2.660    0.000    0.000    0.000
best       9.501    0.000    0.000    0.000    8.225
year       6.373    2.236    1.615    3.465    1.564
25         4.790    0.000    0.000    0.000    0.000
...          ...      ...      ...      ...      ...
newlook    0.000    0.000    0.000    0.000    0.000
code       0.000    0.168    0.014    0.000    0.014
identif    0.000    0.000    0.000    0.000    0.000
coat       0.000    0.005    0.000    0.000    0.000
flavour    0.000    0.000    0.000    0.000    0.000

[9635 rows x 5 columns]

---
### Machine Learning Foundation (C) 2020 IBM Corporation